"""
Email Generator for Invoice Payment Manager
Creates formatted emails for vendor communication
"""

from datetime import datetime, timedelta


def format_original_email(request):
    """
    Format the original vendor request email
    
    Args:
        request: Dictionary containing request information
    
    Returns:
        Formatted email string
    """
    request_id = request.get('request_id', 'N/A')
    vendor_name = request.get('vendor_name', 'Unknown Vendor')
    amount = float(request.get('invoice_amount', 0))
    due_date = request.get('original_due_date', 'N/A')
    extension_days = request.get('requested_extension_days', 0)
    reason = request.get('reason', 'No reason provided')
    submission_date = request.get('submission_date', datetime.now().strftime('%Y-%m-%d'))
    
    email = f"""━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ORIGINAL REQUEST FROM VENDOR
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

From: {vendor_name} <vendor@{vendor_name.lower().replace(' ', '')}.com>
To: accounts@company.com
Date: {submission_date}
Subject: Payment Extension Request - Invoice #{request_id}

Dear Accounts Payable Team,

We are writing to request an extension for payment of 
invoice #{request_id}.

Invoice Details:
- Amount: ${amount:,.2f}
- Current Due Date: {due_date}
- Requested Extension: {extension_days} days

Reason for Extension:
{reason}

We appreciate your understanding and look forward to your 
prompt response.

Best regards,
{vendor_name}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"""
    
    return email


def generate_approval_email(request, ai_result):
    """
    Generate approval email for vendor
    
    Args:
        request: Dictionary containing request information
        ai_result: Dictionary with AI decision details
    
    Returns:
        Formatted approval email string
    """
    request_id = request.get('request_id', 'N/A')
    vendor_name = request.get('vendor_name', 'Unknown Vendor')
    amount = float(request.get('invoice_amount', 0))
    original_due_date = request.get('original_due_date', 'N/A')
    extension_days = int(request.get('requested_extension_days', 0))
    
    # Calculate new due date
    try:
        if isinstance(original_due_date, str):
            due_date_obj = datetime.strptime(original_due_date, '%Y-%m-%d')
        else:
            due_date_obj = original_due_date
        new_due_date = due_date_obj + timedelta(days=extension_days)
        new_due_date_str = new_due_date.strftime('%Y-%m-%d')
    except:
        new_due_date_str = 'TBD'
    
    today = datetime.now().strftime('%Y-%m-%d')
    confidence = ai_result.get('confidence_score', 0) * 100
    processing_time = ai_result.get('processing_time', 0)
    
    email = f"""Subject: Payment Extension Approved - Invoice #{request_id}

Dear {vendor_name},

We are pleased to inform you that your request for a payment 
extension has been APPROVED.

REQUEST DETAILS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Request ID:           {request_id}
Invoice Amount:       ${amount:,.2f}
Original Due Date:    {original_due_date}
Extension Period:     {extension_days} days
New Due Date:         {new_due_date_str}

APPROVAL DETAILS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Decision Date:        {today}
Confidence Score:     {confidence:.0f}%
Processing Time:      {processing_time:.1f} seconds

Your payment is now due by {new_due_date_str}. We appreciate your 
continued partnership and look forward to receiving payment by 
the new due date.

IMPORTANT REMINDERS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Please ensure payment is made by {new_due_date_str}
• Reference invoice #{request_id} in your payment
• Contact us immediately if you anticipate further delays
• This extension is granted as a one-time courtesy

If you have any questions about this approval or need further 
assistance, please don't hesitate to contact our Accounts 
Payable team.

Best regards,

Accounts Payable Department
Shared Service Center
Phone: (555) 123-4567
Email: accounts.payable@company.com

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This email was generated by Invoice AI Agent - Powered by Keboola
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"""
    
    return email


def generate_rejection_email(request, ai_result):
    """
    Generate rejection email for vendor
    
    Args:
        request: Dictionary containing request information
        ai_result: Dictionary with AI decision details
    
    Returns:
        Formatted rejection email string
    """
    request_id = request.get('request_id', 'N/A')
    vendor_name = request.get('vendor_name', 'Unknown Vendor')
    amount = float(request.get('invoice_amount', 0))
    original_due_date = request.get('original_due_date', 'N/A')
    extension_days = int(request.get('requested_extension_days', 0))
    reason = request.get('reason', 'No reason provided')
    
    today = datetime.now().strftime('%Y-%m-%d')
    ai_reasoning = ai_result.get('reasoning', 'Request does not meet approval criteria')
    
    email = f"""Subject: Payment Extension Request - Unable to Approve #{request_id}

Dear {vendor_name},

After careful review, we regret to inform you that we are 
UNABLE TO APPROVE your request for a payment extension at 
this time.

REQUEST DETAILS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Request ID:           {request_id}
Invoice Amount:       ${amount:,.2f}
Original Due Date:    {original_due_date}
Requested Extension:  {extension_days} days
Reason Provided:      {reason}

DECISION DETAILS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Decision Date:        {today}
Risk Assessment:      {ai_reasoning}

NEXT STEPS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Payment remains due on: {original_due_date}
• Please arrange payment by the original due date
• Contact us to discuss alternative payment options
• We're available to explore installment plans if needed

We understand that cash flow challenges can arise, and we're 
committed to working with our valued vendors. Please contact 
our Accounts Payable team to discuss alternative payment 
arrangements that may be available.

ALTERNATIVE OPTIONS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Partial payment plans
• Renegotiate payment terms for future invoices
• Discuss early payment discounts for expedited settlement

We value our partnership with {vendor_name} and want to find 
a solution that works for both parties.

For immediate assistance, please contact:

Accounts Payable Department
Shared Service Center
Phone: (555) 123-4567
Email: accounts.payable@company.com

Best regards,

Accounts Payable Department

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This email was generated by Invoice AI Agent - Powered by Keboola
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"""
    
    return email


def generate_email_response(request, decision, ai_result):
    """
    Generate appropriate email response based on decision
    
    Args:
        request: Dictionary containing request information
        decision: String ('Approved' or 'Rejected')
        ai_result: Dictionary with AI decision details
    
    Returns:
        Formatted email string
    """
    if decision == 'Approved':
        return generate_approval_email(request, ai_result)
    else:
        return generate_rejection_email(request, ai_result)

